### ISSUE TITLE
Compile erros

### ISSUE THREAD

**Issue by YingfangZhou** [OPM/opm-polymer#103]
I was trying to compile OPM-POLYMER and got the following errors, it seems these errors came from opm-autodiff, while the opm-autodiff module has been complied successfully.
```
[  5%] Patching Makefile to be DUNE compatible
[  5%] Built target dune-compat
[ 10%] Updating version information
[ 10%] Built target update-version
[ 70%] Built target opmpolymer
[ 75%] Building CXX object CMakeFiles/flow_polymer.dir/examples/flow_polymer.cpp.o
/home/yz7609/Downloads/opm-polymer/examples/flow_polymer.cpp: In function ‘int main(int, char**)’:
/home/yz7609/Downloads/opm-polymer/examples/flow_polymer.cpp:164:47: error: no matching function for call to ‘Opm::BlackoilOutputWriter::BlackoilOutputWriter(const UnstructuredGrid&, Opm::parameter::ParameterGroup&, std::shared_ptr<Opm::EclipseState>&, const Opm::PhaseUsage&)’
/home/yz7609/Downloads/opm-polymer/examples/flow_polymer.cpp:164:47: note: candidate is:
/usr/local/include/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp:188:9: note: template<class Grid> Opm::BlackoilOutputWriter::BlackoilOutputWriter(const Grid&, const Opm::parameter::ParameterGroup&, Opm::DeckConstPtr, Opm::EclipseStateConstPtr, const Opm::PhaseUsage&)
make[2]: *** [CMakeFiles/flow_polymer.dir/examples/flow_polymer.cpp.o] Error 1
make[1]: *** [CMakeFiles/flow_polymer.dir/all] Error 2
make: *** [all] Error 2
```
Many thanks if anyone could help me out.

Best wishes
Yingfang

**Comment by GitPaean** [comment]
I am not sure about the version of other modules, while it looks like your opm-polymer is not updated. 

Could you please try to update ert, opm-parser, opm-core, (dune-cornerpoint optionally) opm-autodiff, and then opm-polymer then try again?

**Comment by qilicun** [comment]
@YingfangZhou 

I just started a fresh building and find no compile errors happened. So please update all the modules that @GitPaean suggested and report back. Thanks.

**Comment by YingfangZhou** [comment]
@GitPaean & qilicun

Issue has been fixed, please close this issue.

Yingfang

**Comment by GitPaean** [comment]
Thanks for reporting back. Feel free to let us know if you get any other problems.
