### ISSUE TITLE
Generate loops for polymer flooding

### ISSUE THREAD

**Issue by YingfangZhou** [OPM/opm-polymer#106]
I was trying to generate python loops for polymer flooding as that for water flooding model, while it seems this version is not capble to do that. Please could you advise me how to generate loops for polymer flooding senstive study.

Best wishes

Yingfang

**Comment by GitPaean** [comment]
Hi, could you please tell a little more about what you are doing? I am not sure I understand `python loops`. Thanks.

**Comment by alfbr** [comment]
Are you trying to run several cases in batch from a Python script? If so, the most straight forward way is to interface with the input and output files from the flow simulator.

**Comment by YingfangZhou** [comment]
I was using the following command in python,
args = ("/home/yz7609/Downloads/OPM/opm-polymer-build/bin/flow_polymer", file_name)
The file_name was defined in the cases.

**Comment by alfbr** [comment]
and you have confirmed that running
/home/yz7609/Downloads/OPM/opm-polymer-build/bin/flow_polymer file_name
directly from the commanline works?

**Comment by qilicun** [comment]
@YingfangZhou 
In general, run flow_polymer you should use the following command.
``
./flow_polymer deck_filename=example.DATA
``
Good luck!
