### ISSUE TITLE
Polymer test case fails

### ISSUE THREAD

**Issue by flikka** [OPM/opm-polymer#160]
The case at https://github.com/OPM/opm-data/tree/master/polymer_test_suite/simple2D seems to fail now - see for example https://ci.opm-project.org/job/polymer-test-simple-2d/559/console

This seems to have started after the PR https://github.com/OPM/opm-autodiff/pull/536

Anyone that knows what's happening, and why?

**Comment by GitPaean** [comment]
I did not reproduce the problem. Did anyone reproduce the problem?

**Comment by atgeirr** [comment]
I can reproduce this. Will look into it.

**Comment by atgeirr** [comment]
I also noticed that I did not get an email about this -- the job was not configure to send email upon failures. I have addressed that (for the opm-polymer job, there may be other jobs that fail without any emails being sent).

**Comment by bska** [comment]
> I can reproduce this. Will look into it.

I see this too when I run the example as
```
${exe} path/to/2D_THREEPHASE_POLY_HETER.DATA use_cpr=false
```
with `exe` being the full path to a release-mode sequential build of `flow_polymer` targeting Dune 2.3.1.  Just looking at the residuals there appears to be some kind of oscillating behaviour during the first timestep and everything is downhill from there.

**Comment by bska** [comment]
If I run this in debug mode I get treated to a nice `assert()` failure.  This may or may not be related to the same issue.
```
flow_polymer: /home/bska/work/opm/src/opm/opm-autodiff/opm/autodiff/BlackoilModelBase_impl.hpp:1950: void Opm::BlackoilModelBase<Grid, Implementation>::updateState(const V&, Opm::BlackoilModelBase<Grid, Implementation>::ReservoirState&, Opm::BlackoilModelBase<Grid, Implementation>::WellState&) [with Grid = UnstructuredGrid; Implementation = Opm::BlackoilPolymerModel<UnstructuredGrid>; Opm::BlackoilModelBase<Grid, Implementation>::V = Eigen::Array<double, -1, 1>; Opm::BlackoilModelBase<Grid, Implementation>::ReservoirState = Opm::PolymerBlackoilState; Opm::BlackoilModelBase<Grid, Implementation>::WellState = Opm::WellStateFullyImplicitBlackoilPolymer]: Assertion `varstart == dx.size()' failed.
Aborted (core dumped)
```

**Comment by atgeirr** [comment]
Bug found, fixed. PR in OPM/opm-autodiff#540.

**Comment by flikka** [comment]
Excellent - @atgeirr - I've added you to the config for this job (and the SPE test jobs)
