### ISSUE TITLE
opm-polymer does not compile/work with Dune 2.3

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-polymer#47]
See http://opm-project.org/CDash/index.php?project=opm-polymer

Since Dune 2.3 is going to be released soon, this issue should be fixed before the OPM 2014.03 release...

**Comment by dr-robertk** [comment]
I just did compile with Dune 2.3.1, so maybe this issue is obsolete.

**Comment by andlaus** [comment]
it is. has been for quite a while, actually...
