### ISSUE TITLE
Blindly assuming opm-autodiff supports cpgrid

### ISSUE THREAD

**Issue by akva2** [OPM/opm-polymer#79]
In opm-autodiff, certain symbols are compiled depending on whether or not dune-cornerpoint is available (UgHelpers stuff). the examples here blindly use these functions (which should not have been prototyped in the first place, but that's another issue..) and thus you get  very cryptic linker error.

Dead-symbol pruning hides the issue with static libs thus most never see this.

not really a show stopper as such, but figured it was worth documenting.

**Comment by atgeirr** [comment]
I think this has been resolved by moving the prototypes to dune-cornerpoint, closing.
