### ISSUE TITLE
Eigen not found if autoinstalled Eigen is used.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-polymer#94]
CI get the following error when trying to compile opm-polymer:

```
opm-autodiff/opm/autodiff/AutoDiffBlock.hpp:25:23: fatal error: Eigen/Eigen: No such file or directory
```
```C++
 #include<Eigen/Eigen>
```                       
Creating the corresponding link to `opm-autodiff/eigen3-installed/include/eigen3/Eigen/` helps but is probably not the intended solution.

**Comment by qilicun** [comment]
I have never try this before, but the sibling build works fine.

**Comment by bska** [comment]
>
```
opm-autodiff/opm/autodiff/AutoDiffBlock.hpp:25:23: fatal error: Eigen/Eigen: No such file or directory
```

If this problem still exists then I'd be inclined to say it is a local issue on the continuous integration system.  The documentation of [Eigen 3](http://eigen.tuxfamily.org/dox/group__QuickRefPage.html) explicitly states that
```C++
#include <Eigen/Eigen>
```
is how one is supposed to access the (whole of the) Eigen library.

What does "autoinstalled Eigen" mean, anyway?

**Comment by atgeirr** [comment]
> What does "autoinstalled Eigen" mean, anyway?

I think he refers to the ability of the opm-autodiff build system to download Eigen if it's not found. The problem then seems to be that this is not found by downstream modules.

**Comment by atgeirr** [comment]
There is probably no easy solution to this problem (unless @akva2 has a good idea), I suggest that we for now require an Eigen installation for opm-polymer (so that opm-autodiff will use that one, too).

**Comment by dr-robertk** [comment]
I was going to make the necessary changes due to ParallelDebugOutput in opm-polymer, but due to the still not working Eigen stuff, I can't.

**Comment by atgeirr** [comment]
This is a problem with the autoinstalled Eigen, not opm-polymer, the feature is broken (for all purposes but just building opm-autodiff). You should install an Eigen package for your OS/distro instead. I stand by my earlier view:

> I suggest that we for now require an Eigen installation

... instead of relying on the autoinstall.

**Comment by atgeirr** [comment]
> the necessary changes due to ParallelDebugOutput in opm-polymer

About this, I think I'll start doing a refactoring of these programs now, to eliminate duplication. About time? For now, flow_polymer will not run in parallel so it does not matter. After refactoring it should work.

**Comment by bska** [comment]
> You should install an Eigen package for your OS/distro instead.

In a pinch you can clone https://github.com/OPM/eigen3 as a sibling directory of the OPM modules.

**Comment by alfbr** [comment]
When the autoinstall of Eigen was done we were in a situation where none of our target distributions packaged the necessary version of Eigen. This situation may have changed? Still, the autoinstall of Eigen has worked flawlessly since the beginning, ensuring that nobody were bitten by that dependency.

**Comment by dr-robertk** [comment]
Of course I could install a version of Eigen or as @bska suggested, I
could also install the Eigen version from the repository.

I like the autoinstalled version, and I just wanted to point out that is
does not work with other packages except opm-autodiff.

--
Sendt fra min brødrister

**Comment by alfbr** [comment]
There are multiple quick fixes to that. One is to just duplicate the autoinstall logic in opm-polymer. Another is to move the Eigen dependent polymer simulator to the autodiff repo. Neither very elegant, but they would solver it with minimum effort. Alternatively we can abolish autoinstall in favour of a package dependency (but then Eigen should be available in key distros). Lastly we can re-engineer the autoinstall to cater to the multiple repo scenario.

**Comment by atgeirr** [comment]
Moving opm-polymer into opm-autodiff should be done anyway in my opinion (a step in the suggested reorganization), so perhaps we should do this now?

**Comment by qilicun** [comment]
I think merging opm-autodiff and opm-polymer is a good idea, since we now have solvent model in opm-autodiff. But polymer properties  in opm-polymer have AD and non-AD type which should be taken care of.

**Comment by alfbr** [comment]
Sounds like we are converging to a solution. I support gathering the simulators under one roof too.

**Comment by atgeirr** [comment]
I would make a proposal, but for the fact that I'll be travelling next week. Can someone else pick this up?

> But polymer properties in opm-polymer have AD and non-AD type which should be taken care of.

I do not think this is a problem for merging modules.

**Comment by qilicun** [comment]
>I do not think this is a problem for merging modules.

Yes, that's true. But I was thinking non-AD type properties and solver could be moved to the other modules, e.g opm-core.

**Comment by atgeirr** [comment]
Since we have decided that moving the polymer simulator into opm-autodiff will not happen before the release, we are left with the question of what to do with this issue. I suggest: nothing, it will be resolved shortly after release. It is a problem only for those building from source that do not have Eigen installed on their system, who I would expect mostly would use the current master and not release branches.

**Comment by atgeirr** [comment]
Since we have agreed to move opm-polymer into opm-autodiff, I'll close this issue. It has been added as an issue in opm-autodiff.
